name: Upload coverage reports to Codecov
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  pull_request:
    branches:
      - alpha
      - beta
      - master
jobs:
  upload-test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch_name
        run: echo "branch=$(echo ${GITHUB_HEAD_REF#refs/heads/})" >>$GITHUB_OUTPUT

      - name: Checkout ${{ steps.branch_name.outputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch_name.outputs.branch }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - name: Install dependencies
        run: npm install

      - name: Run tests
        if: always()
        run: npm run test:all

      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
